### ISSUE TITLE
Cannot save after ingredient rename

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#106]
**Describe the bug**
ingredient save silent fail if you change ingredient name

**To Reproduce**
- open ingredient edit modal
- actions -> rename ingredient -> click rename -> click close
-  change any other data -> click save

**Expected behavior**
save all edited fields

-

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 16.6 (18615.3.12.11.2)

**Comment by SimoneCarnio** [comment]
I think the problem is that ing post field is statically assigned from php in mgmingredient.php, should be replaced with a var in js and updated after success event of ingredient rename (also ingredients list should be refreshed)

```
<?php if($ing['name']){?>
					ing: '<?=$ing['name'];?>'
<?php } ?>
```

**Comment by globaldyne** [comment]
That's pretty much expected as the data don't automatically refresh unless the user clicks the link pointing to the new name.

**Comment by globaldyne** [comment]
I have added an automatic redirection to the new ingredient upon successful rename, so the data will be able to updated now.

**Comment by SimoneCarnio** [comment]
You anticipated my suggestion, I hadn't noticed the link, with a redirect I think it's less confusing 
👍🏻
