### ISSUE TITLE
additional fields for ingredients identification

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#107]
**Is your feature request related to a problem? Please describe.**
to identify more quickly where the ingredients are stored e where they where purchaesd, it would be interesting to add some fields related to internal cataloging

**Describe the solution you'd like**
Additional fields  in the "Add supplier for xxxx" modali (inside ingredient details) would be useful, such as:

- Internal ingredient sku 
- Supplier product sku 
- Location/Cabinet/Bookshelf (Useful to know where the products are stored)

All fields should be included in the ingredients json export for further processing. (For example, I use the json to print in batch bottle and cap labels)

**Describe alternatives you've considered**
none

**Additional context**

<img width="564" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/e0e72cfb-7d1c-4362-af38-4ad7e3f482d2">

**Comment by globaldyne** [comment]
Good suggestion, added in 8.4
