### ISSUE TITLE
URL field mandatory discrepancy

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#108]
**Describe the bug**

When you add a new supplier to and ingredients the URL field is mandatory; once you saved, you can edit and insert an empty URL.

**To Reproduce**

- add new supplier and fill the URL else you cannot save
- edit the URL in the supplier list
- clear the text area
- save

**Expected behavior**

URL should not be mandatory in my opinion, some supplier don't have eshop o online catalog, to be evaluated whether to also include the "none" option in the platform field in the details of the supplier

**Screenshots**

<img width="575" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/8f51ba4e-1002-40ec-9e28-f1ba3f8ccda2">

<img width="510" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/b220673c-84da-4ccc-b60f-ce2279e7457f">

<img width="321" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/76352044-c95d-486c-87fc-7cd39c7606e4">

**Comment by globaldyne** [comment]
Fixed in 8.4

**Comment by SimoneCarnio** [comment]
Just a question, why not implement a "no shop" option and remove the mandatory nature of the field?
