### ISSUE TITLE
Strange behaviour in "make formula"

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#113]
**Describe the bug**
By inserting a higher amount of product the result becomes negative

**To Reproduce**
see screenshot

**Expected behavior**
Maybe the field should be limited at the remaining maximum amount?

**Screenshots**
<img width="1153" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/34ed56d4-8bed-428c-837f-ccb9e685fefc">

<img width="613" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/36bd1fd5-1141-478e-a607-2349d24dfc29">

<img width="1146" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/cdd7f636-ce9f-4034-87a5-3a24c70d7b30">

**Comment by SimoneCarnio** [comment]
Another question, when you insert a note, when/where it's used?

<img width="520" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/dbe8c41e-718d-47db-adab-41f0123c5d87">

**Comment by globaldyne** [comment]
The negative value is actually happening on purpose to mark the material is overdosed, note that the message returns that the material is overdosed and there's a warning next to it as well.
Notes will go to the general formula notes - see settings section.

**Comment by SimoneCarnio** [comment]
Ok, now I think I understood the discourse of the notes (not the reference to the settings).

I would like to note then that a new line should be added when the notes are joined 

<img width="436" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/a6c4da13-8ca7-476d-8ace-9eb01e3bd7b1">

**Comment by SimoneCarnio** [comment]
also when "overdosing" values are saved to notes'
but without any reference to the ingredients

<img width="264" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/0056eccc-77e7-456e-8ef2-67a1c99a5da0">


Maybe save these kind of notes in separate rows?

**Comment by SimoneCarnio** [comment]
When overdosing you cannot make formula as complete. I cannot roll back overdosing so how can set as made the formula?


<img width="1362" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/ed844a8b-8fd9-4e0c-aecf-429ce6ed2adb">
