### ISSUE TITLE
145 Vulnerabilities in Docker

### ISSUE THREAD

**Issue by mjudi** [globaldyne/parfumvault#122]
**Describe the bug**
After I installed the app in Docker, 145 vulnerabilities were reported. Is this something I should be concerned about and how to address these vulnerabilities?

**To Reproduce**
These vulnerabilities will show up right away after installing Docker.

**Expected behavior**
I would expect the app to be safe with no security issues.

**Screenshots**
![image](https://github.com/globaldyne/parfumvault/assets/7775966/f7a8b471-3cde-44d3-b32e-9d9d8cc9ed3f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 117.0.2045.60 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.0.3
 - Browser Safari
 - Version

**Additional context**

**Comment by globaldyne** [comment]
Seems like you using an image from a deprecated repo, use this one instead

https://hub.docker.com/r/globaldyne/perfumersvault

**Comment by mjudi** [comment]
Hi John,

 

Thank you for your quick feedback. I pulled the latest image but I’m still seeing vulnerabilities in Docker. Is that OK?

 



 

Best regards,



 

M 647.388.2740 ● E ***@***.***
