### ISSUE TITLE
Saved information is changing for new suppliers

### ISSUE THREAD

**Issue by mjudi** [globaldyne/parfumvault#124]
**Describe the bug**
When I enter a new supplier into the list, the information about the supplier changes after I save it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new supplier
2. Enter the information pertaining to the supplier
3. Save
4. Go to another screen (for example to formulas) and come back to edit that supplier.

**Expected behaviour**
I'm expecting to find the information I entered but I found it changed.

**Screenshots**
![image](https://github.com/globaldyne/parfumvault/assets/7775966/887f3c25-84c2-4075-a73c-c33941265417)
![image](https://github.com/globaldyne/parfumvault/assets/7775966/cd17017f-0ce4-4d58-8078-96f337fcc25b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 118.0.2088.46 (Official build) (64-bit)

**Additional context**

**Comment by globaldyne** [comment]
Seems like there's a bug when adding a new supplier failing to populate the those fields. Will be addressed in the next release. As a workaround you can use the edit option once the supplier is created.
