### ISSUE TITLE
PVOnline search broken

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#128]
**Describe the bug**
PVOnline search never gives back any results

**To Reproduce**
1. Go to ingredients inventory
2. switch search to PVOnline
3. do any search

**Screenshot**
<img width="1212" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/2d4edf49-0d98-4ff7-9c36-f2e1f3de2281">

**Expected behavior**
some results

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Comment by globaldyne** [comment]
I am unable to replicate the issue. 
Can you please make sure you always provide the PV version when you raising a bug?

**Comment by SimoneCarnio** [comment]
Forgot it, anyway is the latest 8.9.
Just tried it now and it works, 2 hours ago was still broken
