### ISSUE TITLE
profil is missing from PVOnline results

### ISSUE THREAD

**Issue by SimoneCarnio** [globaldyne/parfumvault#129]
**Describe the bug**
the "profile" fields results from PVOnline api is always missing from every ingredient

**To Reproduce**
1. go to ingredients inventory
2. switch to PVOnline search
3. search any ingredient
4. profile fields is always unknown

**Expected behavior**
correct profile value as with previous versione of the api

**Screenshots**
<img width="1148" alt="image" src="https://github.com/globaldyne/parfumvault/assets/8537252/252a48b2-1aec-48b3-9923-0b464e21f164">

**Additional context**
PV version 8.9

"profile" fields is missing from the api response in /modules/suppliers/pvOnline.php on pvPost($pvOnlineAPI, $data), 

this is a _print_r_ of one record:

  ```
  [16] => stdClass Object
                (
                    [id] => 2033
                    [cid] => 83268
                    [name] => Dimetol
                    [IUPAC] => 2,6-dimethylheptan-2-ol
                    [INCI] => 2,6-dimethylheptan-2-ol
                    [cas] => 13254-34-7
                    [einecs] => 236-244-1
                    [odor] => Fresh dihydrolinalool floral woody citrus herbal
                    [allergen] => 0
                    [physical_state] => 1
                    [structure] => iVBORw0KGgoAAAANSUhEUgA.... ..... TkSuQmCC
                    [techData] => stdClass Object
                        (
                            [XLogP] => 2.7
                            [formula] => C9H20O
                            [flash_point] => N/A
                            [molecular_weight] => 144.25
                        )

                    [ifra] => stdClass Object
                        (
                            [id] => 0
                        )

                )
```

**Comment by globaldyne** [comment]
Not a bug, profile field isn't available in PV Online

**Comment by SimoneCarnio** [comment]
But it was available on previous api
