### ISSUE TITLE
Can't update to release 9.0

### ISSUE THREAD

**Issue by mjudi** [globaldyne/parfumvault#132]
**Describe the bug**
A message saying a new release 9.0 is available and when I click on update, I get the following message "Unable to update as home directory is not writable. Please make sure you have write permissions on your server." We need instructions on how to update PV to the new release 9.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Dashboard home page, and you will find this message at the top of the page "New version (9.0) is available! Upgrade available."
2. Click on the Upgrade available hyperlink.
3. See the error "Unable to update as home directory is not writable. Please make sure you have write permissions on your server."

**Expected behaviour**
To be able to upgrade to the new release without issues.

**Screenshots**
![image](https://github.com/globaldyne/parfumvault/assets/7775966/4177620b-0c53-4462-ae44-a8bad14e7c11)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 118.0.2088.76 (Official build) (64-bit)

**Additional context**

**Comment by globaldyne** [comment]
Resolved in version 9.1
