### ISSUE TITLE
Right alignment of the Ingredient Category descriptions with not way to scroll right

### ISSUE THREAD

**Issue by mjudi** [globaldyne/parfumvault#133]
**Describe the bug**
When setting up the Ingredient Categories, in the Settings, the descriptions are right aligned and mostly truncated on the screen. See the screenshot to see the issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings > Ingredient Categories
2. Enter a few categories with their descriptions.
3. When you view the list of categories, you will notice that the descriptions are aligned to the right outside the scope of the screen. See screenshot.

**Expected behaviour**
The descriptions are listed properly within the scope of the screen preferably left aligned.

**Screenshots**
![image](https://github.com/globaldyne/parfumvault/assets/7775966/26d91ed0-395f-4bb2-96f1-62254f1729a7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 118.0.2088.76 (Official build) (64-bit)

**Additional context**

**Additional context**

**Comment by globaldyne** [comment]
Fixed
