### ISSUE TITLE
Formulas not showing past 100

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#136]
**Describe the bug**
Formulas doesnt show in total, lets say I have 200+ formulas and default its showing 20 per page. There is only 1 page, so cannot see more than 20 Formulas, unless choosing to see 100 per page, but still I cannot see remaining formulas. Because there is only 1 page and cant click next.

**To Reproduce**
1. Go to formula management, and then formula and you will see default 20 showing pr. site as default. Go to bottom of site and try and click next page, it wont because it think there is only one page, so go up and click drop down in show entries where it says 20 and choose 100 and you can see 100 but not the remaining 100+

3. Click on
4. Scroll down to
5. See error

**Expected behavior**
Expected behavior would be to see all formulas and be able to navigate by clicking next page, and also be able to see all formulas be put into the right and defined categories.

**Screenshots**
![9 2](https://github.com/globaldyne/parfumvault/assets/74374799/6e279645-80ec-4a6e-8a32-063cddc9ed9e)

**Please complete the following information:**
 - Platform: docker
 - Browser all browsers
 - PV Version 9.2

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
If formulas not showing properly try to remove any user preferences set, you will find an option to that under the maintenance tab in the settings page.

Please open another bug for the other issue, don't raise multiple things together as its not easy to be tracked.

**Comment by xblomx** [comment]
Ive tried recreating all, exporting importing, starting clean.. but error remains. It works up until v9.0 and after upgrading to v9.1 and forward the problem shows. Would be really nice to have this fixed, as I would like to stay on latest release.

**Comment by globaldyne** [comment]
This has been addressed in the latest release (v9.4)

**Comment by xblomx** [comment]
You are a star 💫💫💫
