### ISSUE TITLE
Formulas not showing on categories

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#138]
**Describe the bug**

The categories ive created, and sorted my formulas into, like floral, woody, fresh, oriental, cyphre etc No formulas are sorted into the right categories, all formulas shows in each category. This has been like this for long, and I hoped eventuelly it would be sorted, but still this bug hasnt been looked into or discovered.

**To Reproduce**
1. Go to Formulas and see categories

**Expected behavior**

Expect that formulas shows in the defined categories, lets say woody and all formulas in that category would show ø, right now its mixed.

**Screenshots**

**Please complete the following information:**
 - Platform: docker
 - Browser all browsers
 - PV Version 9.1

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
Make sure you have (re)set the gender as well when you allocating a category

**Comment by xblomx** [comment]
Yes ive tried all those suggestions

**Comment by xblomx** [comment]
Ive tried recreating all, exporting importing, starting clean.. but error remains. It works up until v9.0 and after upgrading to v9.1 and forward the problem shows. Would be really nice to have this fixed, as I would like to stay on latest release.
