### ISSUE TITLE
Formulas page not changing when clicking page 2 etc

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#153]
**Describe the bug**

When at Formulas page, and clicking next to page 2 or 3 etc the formulas doesnt change, but still show default 20 formulas, that you see on page 1. I can change that to 100 views and still cannot change to page 2 seeing the next row of 100

**To Reproduce**
1. Go to '...' Formula Management -> Formulas
2. Click on '....' If you have more formulas than can be shown on page 1, 20-100 formulas and click page 2 to see next batch of fomulas 21 or 101 and click next no formulas is changing
3. Scroll down to '....' Where you can click next to see next batch of formulas 
4. See error, no formulas shows

**Expected behavior**
I would expect that the next batch of formulas shows, and not staying on the same formulas view as in page 1 but show the next batch of formulars

**Screenshots**

**Please complete the following information:**
 - Platform: [e.g. docker] docker
 - Browser [e.g. chrome, safari] all browser
 - PV Version [e.g. 9.1] v9.5

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
Fixed in version 9.6
