### ISSUE TITLE
Generate Finished Product no export to PDF etc

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#154]
**Describe the bug**
When Generate Finished Product and go to Actions, where you can Export to PDF and Print Label and Print Box Label and last View Box Label as Text, none of those features works, at least not Export to PDF and View Box Label as Text, it worked in version 9.4

**To Reproduce**
1. Go to '...' Generate Finished Product
2. Click on '....' Actions
3. Scroll down to '....' either option, Export to PDF or View Label as Text
4. See error They dont work

**Expected behavior**

I would expect that the Export to PDF and View Label as Text would work.

**Screenshots**
![2024-02-25 14 14 37](https://github.com/globaldyne/parfumvault/assets/74374799/f13e311a-ee14-4fe2-92e2-30c30293e6cc)

**Please complete the following information:**
 - Platform: [e.g. docker] docker
 - Browser [e.g. chrome, safari] all browsers
 - PV Version [e.g. 9.1] 9.5

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by AbstractActs** [comment]
Yeah, and their is no generate IFRA certificate on this page. I commented that this was the case in 7.9 which I was using and weas told to pull the latest version but it has the same problems. No IFRA certificate and unable to export to PDF from that menu.

**Comment by globaldyne** [comment]
This will be addressed in the new release.

**Comment by AbstractActs** [comment]
when will the new release be out?

**Comment by globaldyne** [comment]
Not planned yet, you can keep an eye in the demo as this always a version ahead
https://www.perfumersvault.com/try-out-pv/

**Comment by AbstractActs** [comment]
does the Ifra certificate generation work in an earlierer version? I need to send some to my chemist.

**Comment by globaldyne** [comment]
Fixed in version 9.8
