### ISSUE TITLE
No generate IFRA certificate in v9.5 and no export to PDF in the same menu

### ISSUE THREAD

**Issue by AbstractActs** [globaldyne/parfumvault#155]
**Describe the bug**
Generate IFRA certificate has been removed from v9.5 and you cant export finished perfume to PDF

**To Reproduce**
1. Go to '...' finished product
2. Click on '....' actions
3. Scroll down to '....' generate PDF is nolonger a feature
4. See error unable to export to PDF

**Expected behavior**
A clear and concise description of what you expected to happen. To have the ability to generate an IFRA Certificate for the perfume and export fininshed perfume to PDF

**Screenshots**

**Please complete the following information:**
 - Platform: [e.g. docker] DOCKER
 - Browser [e.g. chrome, safari] Chrome/Firefox
 - PV Version [e.g. 9.1] V 9.5

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
Fixed in version 9.8
