### ISSUE TITLE
Adding ingredients to formular not showing as added

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#161]
**Describe the bug**
When adding ingredients to formulars it doesnt show its added, not in prompt neither in the formular it self.

**To Reproduce**
1. Go to '...' Creat a new formular, then go adding ingredients
2. Click on '....' add
3. Scroll down to '....' youll see its not showing as added
4. See error same as above

**Expected behavior**
I would expect to see its added to the formular, and also a prompt indication its been added

**Screenshots**

**Please complete the following information:**
 - Platform: [e.g. docker] docker
 - Browser [e.g. chrome, safari] all browsers
 - PV Version [e.g. 9.1] PV Version 9.7

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by xblomx** [comment]
Any comment on this?

**Comment by globaldyne** [comment]
That affects only new installations, will be addressed on the next release.

**Comment by globaldyne** [comment]
Fixed
