### ISSUE TITLE
Connexion problem to DB

### ISSUE THREAD

**Issue by guy-bouchard** [globaldyne/parfumvault#189]
**Describe the bug**
I'm trying to install Parfumers Vault an I can't figure out what i'm doing wrong.
-First I tried on my Mac with Mac/Linux script just to see if the software would fit my needs but it doesn't work because the script didn't find Docker.
-I didn't want to debug since  my goa is to install this software on my Docker server.
-I tried to install it via Portainer on my docker LXC with the Default Docker Compose file, I only change the external port to 8080, the Stack deploy without any issue but when I tried to connect to the web site It always return the same error: {"error":"DB Schema Creation error. Make sure the database pvault exists in your mysql server ####, user pvault has full permissions on it and its empty."}
-Then I removed the Database settings in the Docker file and tried to connect directly to my MariaDB Docker, I received the same error and ironically the database is populate with all the table it required the installation script connect and prepare the database.
-I then thought it could be one of those Portainer tricks. and tried to install with the script directly on the Linux LXC which contain Docker, Docker Compose and portainer, the script return and error it can't find Docker... I tried on another LXC on another box, same problem.
-I return to my Mac debug and update Docker install wget and what need to run the script, it installed well but when I try to connect to the web server, same error: {"error":"DB Schema Creation error. Make sure the database pvault exists in your mysql server , user pvault has full permissions on it and its empty."}
-I noticed that version 11.5 was release only a day ago so I suspected a glitch, I installed version 11.4 with the vanilla Docker file. Same result:{"error":"DB Schema Creation error. Make sure the database pvault exists in your mysql server #####, user pvault has full permissions on it and its empty."}

**To Reproduce**
I would say that the easiest installation which have less variables is plain mac script:
sh -c "$(curl -fsSL https://raw.githubusercontent.com/globaldyne/parfumvault/master/helpers/run_pvault.sh)"

**Expected behavior**
Be able to connect to http://localhost:8000/login.php without this error:
{"error":"DB Schema Creation error. Make sure the database pvault exists in your mysql server pvdb, user pvault has full permissions on it and its empty."}

**Please complete the following information:**
 - Docker
 4.34.2 (167172)
 - Brave 
[Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (arm64)](https://brave.com/latest/)
 - PV Version
 Perfumer's Vault Ver 11.5
-MacBookPro
 Apple M1 MAX
- Mac version
 Sonoma 14.6

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
Seems like there's a bug affecting new installation for versions 11.4 and 11.5. This will be addressed 11.6
Meanwhile as a workaround, you can install 11.3 and then upgrade to 11.5
