### ISSUE TITLE
Creating a finished product error

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#191]
**Describe the bug**
When trying to create a finished product this error pops up

DataTables warning: table id=formula - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**To Reproduce**
1. Go to '...' Formula management
2. Click on '....' Finished Product
3. Scroll down to '....' Fill in needed and click generate

**Expected behavior**

Expected behavior is that a finished product is generated with batch id etc

**Screenshots**

**Please complete the following information:**
 - Platform: [e.g. docker] Docker
 - Browser [e.g. chrome, safari] all browsers
 - PV Version [e.g. 9.1] latest version

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
You have to make sure that all your inventory entries are assigned to a supplier and contains a valid price information (0 isn't accepted as a price)
In a future release Finished Product access will be blocked and will result to an error if incomplete/invalid data detected across the inventory.

**Comment by xblomx** [comment]
Would there be an easier way to add price entries than having to go through 1000+ materials one by one?

. xblomx
