### ISSUE TITLE
Creating ingredient from Accord

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#32]
Saving or converting a formula to ingredients doesn't work if you have # in the name; let's say it's called revision #1. Then it will save, but the ingredients in the composition won't show up. Also, suppose you have yet to be successful, have done it several times, saved with the illegal symbols.. and deleted the newly created ingredient. In that case, it will show up several times as not deleted, so there must also be something conflicting with deletions. If it has signs in the name, that wont work... It would be nice not to have those limitations in naming conventions. I've experienced it with other symbols like" or 'etc...

**Comment by globaldyne** [comment]
This is happening as illegal characters are filtered out in ingredient management. Will update the list to filter only the strictly necessary chars.
Characters like **`** and **"** will be filtered out.

**Comment by xblomx** [comment]
That's unfortunate, because ' and " and # are used heavily.

Another thing is that creating ingrediets, sometimes let's say there is 17 ingredients in the accord and creating ingredients only 10 shows up in the composition tab...

So have to go through all accords concerted to ingredients and recreate...

. xblomx

**Comment by globaldyne** [comment]
You will be able to use # though.
Please open a new issue **providing full details as per guide** as what you describing a different problem.

**Comment by xblomx** [comment]
I will 👌

. xblomx
