### ISSUE TITLE
Creating Ingredients from Accord

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#33]
Ive experienced on several occasions, when creating ingredients from acords that contain let's say 17 different AC's and EO's that when it's converted to ingredients, only 10 shows up in the Compositions tab...

I've also experienced the same happening when selecting creating an accord, only some of the AC's and EO's are showing and not all.

Don't know how to troubleshoot this, but a clue could be that if a aroma chemical and essential oil is being updated in the ingredients list, they somehow based on the update disappear from the accord and ingredients created?

Don't know how else to explain it.

**Comment by globaldyne** [comment]
Can't reproduce it
