### ISSUE TITLE
EU banned materials or restricted materials

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#35]
It would be sweet if there would be an equivalent to the IFRA for EU banned or restricted materials to use.

So that would also be an integrated part of the software solution.

Also, if it would be possible to add addendums to the 49th ifra restriction added, so adding the 50th to the already existing ifra added.

**Comment by globaldyne** [comment]
Not a bug.
Please refer to https://www.jbparfum.com/knowledge-base/
