### ISSUE TITLE
Define own, besides the four already present.

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#38]
Would it be possible having an option added so that I can make more than the already 4 present solutions

So for eacmple I can have these

Eau de toilette (EDT)
Eau de parfum (EDP)
Eau de cologne (EDC)
Parfum
Extrait de parfum
Eau de Senteur
Eau fraiche
Splash and aftershave

And be able to define more if needed with set dilution percentages.

**Comment by globaldyne** [comment]
Implemented.

**Comment by xblomx** [comment]
Yes, but now there is an error coming when trying to add.. I've created a ticket for it also.

Error: Table 'pvault.perfumeTypes' doesn't exist this is the error message
