### ISSUE TITLE
Adding new ingredients 

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#39]
When in a formular and trying to add an ingredient and its not available, I'll create one... But having to create multiple, where the first one was 50% in DPG then adding the next, and its not dilluted, DPG is still selected and I have to change to dilution percent and change 100 to 10 and back to 100 for the field with dilutant is reset.. would be a nice fix if automatically set.

**Comment by globaldyne** [comment]
Please provide context, version, environment, screenshots etc

**Comment by xblomx** [comment]
Docker
Latest version 5.4
Docker on my QNAP

Attached are photos

. xblomx

**Comment by xblomx** [comment]
![Screenshot_20230204_153853_Chrome](https://user-images.githubusercontent.com/74374799/216783453-0e447e54-b4bd-4d6e-bbd2-41d9011462e9.jpg)
![Screenshot_20230204_153936_Chrome](https://user-images.githubusercontent.com/74374799/216783464-fc067f5b-f888-4d0f-a36b-4df79ecd6be3.jpg)

**Comment by xblomx** [comment]
Here images are, dont know of you got them before.

**Comment by globaldyne** [comment]
Seems like a broken update between versions.
Try to login to the database and apply the db schema update manually

db/updates/update_5.3-5.4.sql

**Comment by xblomx** [comment]
Okay, how to login to the database?

I'm running on container station on QNAP and also have portainer installed

I can login via console but executing this command from there gives no such file or directory

. xblomx

**Comment by globaldyne** [comment]
You have to patch that file against the database.
Try this command:

mysql -upvault -ppvault pvault < /var/www/html/db/updates/update_5.3-5.4.sql

**Comment by xblomx** [comment]
Sweet, that did it ;) there were already 4 created edc, edt, edp, and perfume, so all sweet ;)

Thanks a million

. xblomx

**Comment by xblomx** [comment]
John,

I managed to recover from a backup some time ago, lost 14 days..

Installed 5.4 again due to the backup I had, and have updated to 5.5

But I'm getting the same issue with the missing perfume types, and tried the previous reccomended, with no success.

It gives me this error like last, see attached.

How to recreate that table when it's missing from fresh install in 5.4 and 5.5?

That would be really nice to know.

. xblomx
