### ISSUE TITLE
Export to PDF exports to CSV

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#47]
This is latest version 5.5 and accessing through Chrome for macosx. Exporting to PDF exports to CSV.

**Comment by globaldyne** [comment]
Can you please provide context? What you trying to export?
Steps to reproduce and logs or screenshots?
What environment, docker or manual?

**Comment by xblomx** [comment]
It happens if you have exported to CSV first and then want to export to PDF then it exports to CSV.

Happens on laptops, iMac, android phones.

**Comment by globaldyne** [comment]
This will be fixed in the next release, meanwhile as a workaround please use Firefox instead.

**Comment by xblomx** [comment]
Thanks, the file can also be renamed from csv to pdf as a workaround.

👌👌

Med venlig hilsen / Kind regards

Stogies & More / 西格德
