### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#48]
I experienced a huge crash and lost data, which set me back weeks.

During recovery, I tried importing the backup db, and it showed an error, making it impossible to restore through the chrome web interface, so I had to import via ssh, and that's not the most optimal way of doing it.

So I was hoping you would implement a better way of recovering and backup and also, perhaps, make it so that it can be set up as a corn job, so there is a daily backup, for example. Attached is the error given when restoring the backup file.

<img width="795" alt="Skærmbillede 2023-02-18 kl  09 33 38" src="https://user-images.githubusercontent.com/74374799/219857072-818a79e2-dee5-4cd6-b29b-a720a276a5c2.png">

**Comment by globaldyne** [comment]
There's a bug in restore process preventing the file to be restored in vanilla installations. This will be addressed in the next release. Meanwhile as a workaround, you can either use command line to restore the file or take an initial backup and then restore the file you want.

Automatic / scheduled backups its out of the scope of this project, its up to user to setup as its per environment / needs.

**Comment by xblomx** [comment]
Thanks, things went haywire last week, but have managed to restore a backup that get me back, and now I've reentered all data.

So I'm good. Also it was a good learning process. Opgrading and downgrading etc.💫

Love your program, it's valuable and highly appreciated 🙏

Thank you

. xblomx

**Comment by xblomx** [comment]
By the way, could you help me with a script that I can use for a cron job that does the same backup as the manual backup that can be executed?

. xblomx
