### ISSUE TITLE
Registration page to PV Online is off

### ISSUE THREAD

**Issue by drone0021** [globaldyne/parfumvault#52]
![2023-03-14_07h53_22](https://user-images.githubusercontent.com/127827532/224919451-1df1b356-207c-4b41-a9c6-dfb488227c8b.png)

**Comment by globaldyne** [comment]
Direct registration has been deprecated hence the page is been removed.
Please see 
[](https://www.jbparfum.com/knowledge-base/what-is-pv-online/)
