### ISSUE TITLE
Unable to import db

### ISSUE THREAD

**Issue by Xave88** [globaldyne/parfumvault#57]
Apologies if this is the wrong place to post this. 

Using: MacOS 12.0.1, this occurs with both edge and chrome.

I was stuck on version 4.9, and decided to finally do a full reinstall to try to update.
I took a back up beforehand
Reinstalled docker and jbvault, and had the latest version (5.8)
Realised that I couldn't import the backup from v4.9
Reinstalled v4.9 and now it says, "There was an error uploading the file, please try again!"

I have attached an image, and I'm unsure how to proceed.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/29845594/226158237-456dce48-fca6-42f6-8f86-9bebf48ee5d3.png">

**Comment by globaldyne** [comment]
There was a bug in version 4.9 when restoring a backup in vanilla installation.
As a workaround, before you try to restore your backup, got to terminal tab in docker dashboard and run the commands bellow

```
mkdir /var/www/html/tmp
chmod -R 777 /var/www/html/tmp
```

Then try restoring your backup as before.

I will recommend to progressively upgrade versions as 4.9 isn't directly upgradable to 5.8

**Comment by Xave88** [comment]
This worked. Thanks!
