### ISSUE TITLE
Unable to Add Ingredients to Formula

### ISSUE THREAD

**Issue by PhantasticUniverse** [globaldyne/parfumvault#58]
- OS: MacOS 12.0.1
 - Browser: Chrome, Edge
 - Version: v5.8
 
When I open or create a formula, I am unable to add ingredients. Despite my ingredients page being populated, when I type names into the search bar it says, "no ingredient found". 
I have reinstalled and restored from a back up but this did not resolve the issue.

Screenshot attached:
<img width="406" alt="Screen Shot 2023-03-20 at 12 36 42 pm" src="https://user-images.githubusercontent.com/29845594/226234164-1bd5ccb6-b006-4be5-8628-8d71afd30149.png">

**Comment by globaldyne** [comment]
Try clearing your browser's cache or try a different browser and see if that helps.

**Comment by Xave88** [comment]
I have used both Chrome and Edge, Edge seems to perform better, but after clearing caches in both browsers I'm still facing the issue. I also tried adding new ingredients, which works, but the won't show up in the dropdown either.
