### ISSUE TITLE
Ingredients disappeared after upgrade

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#64]
**Describe the bug**
After upgrade to new v6.1 or 6.0 the ingredients doesn't show and yields an error.

I've tried both regular and cloud version and it happens with both versions.

**To Reproduce**
Upgrading to latest version, all went fine but the ingredients are not showing. The attached error shows.

**Expected behavior**
To see ingredients 

**Screenshots**
It's added

**Desktop (please complete the following information):**
 This is happening in both docker on qnap containerstation and in the cloud at a docker.

**Smartphone (please complete the following information):**
 Not related

**Additional context**
Can't add much more info than already described and also as attachment says.
![Screenshot_20230417_153815_Chrome](https://user-images.githubusercontent.com/74374799/232580202-9131b2c0-f23a-4b45-bbac-cadd5eec6238.jpg)

**Comment by globaldyne** [comment]
Unable to reproduce withe the info provided
