### ISSUE TITLE
Ingredients error

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#79]
I have made a fresh installation of version 7.x any version in v7 causes the same problem.

All ingredients has been manually added and works perfect in v6.6 both local and cloud edition.

So after upgrading to v7.x I'm not able to access the ingredients and the attached error shows.

Also if I make a fresh installation and import ingredients from online perfumers vault, the same error shows.

How to get by that?

This is the error showing

DataTables warning: table id=tdDataIng - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by globaldyne** [comment]
Please provide system logs and exact steps to replicate.
Make sure when you submit an issue you follow the guide or will ignored

**Comment by xblomx** [comment]
Can I send a video recording of it?

Also, it's an ingredients_list.php error 500 in console.

. xblomx

**Comment by globaldyne** [comment]
EXACT steps and system logs please

**Comment by xblomx** [comment]
Can you tell me where the system logs are to be found in the cloud version?

. xblomx

**Comment by xblomx** [comment]
So, just a nice followup

I made it work, by making a clean installation of v7.3 cloud and imported only the ingredients list from v6.6 cloud and the fragrances etc.. had to be done in a controlled way and it made it all work.

Strange why an upgrade didn't work and also strange why a clean installation importing the online ingredients didn't work.

But nevertheless it works now fine again

. xblomx
