### ISSUE TITLE
Deleting name of formula creates uneditable blank space

### ISSUE THREAD

**Issue by hjpss** [globaldyne/parfumvault#82]
**Describe the bug**
Deleting the name of a formula creates uneditable blank space that cannot be deleted.

**To Reproduce**
1. Go to formulas
2. Click on settings next to a formula
3. Edit the name of the formula to nothing
4. Save changes

**Expected behavior**
I hoped that it would delete the formula. I was trying everything I could think of to delete a formula, and this was one of my attempts.

**Screenshots**
<img width="960" alt="image" src="https://github.com/globaldyne/parfumvault/assets/87756010/a07f0b9b-51de-4ca7-8e00-e44f4cd3fd84">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 7.5

**Additional context**
I still don't know how to delete a formula.

**Comment by globaldyne** [comment]
Not a bug.
Removing the name of the formula won't delete it. Use the delete option next to formula from the drop-down menu (the 3-dots)
