### ISSUE TITLE
No backup after upgrade to v8.0

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#93]
After upgrading to version 8.0 the backup doesnt work any more, it only gives you a backup with a sql file in it with the following details.

-- MySQL dump 10.13  Distrib 8.0.32, for Linux (x86_64)
--
-- Host: 172.17.0.2    Database: pvault
-- ------------------------------------------------------
-- Server version	5.5.5-10.5.21-MariaDB-1:10.5.21+maria~ubu2004

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `IFRACategories`
--

DROP TABLE IF EXISTS `IFRACategories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `IFRACategories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `type` int(11) NOT NULL COMMENT '1=Standard, 2=Custom',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `IFRACategories`
--

LOCK TABLES `IFRACategories` WRITE;
/*!40000 ALTER TABLE `IFRACategories` DISABLE KEYS */;
INSERT INTO `IFRACategories` VALUES (1,'1','Toys, Lip products of all types (solid and liquid lipsticks, balms, clear or colored, etc).',1),(2,'2','Deodorant and antiperspirant products of all types (sprays, roll-on, stick, under-arm and body, etc).',1),(3,'3','Hydroalcoholic products (EdT and fine fragrance range) applied to recently shaved skin (3A and 3B), Eye products of all types including eye cream, mens facial creams and balms (3C), and tampons (3D).',1),(4,'4','Hydroalcoholic products (including scent strips) (EdT and fine fragrance range) applied to unshaved skin, ingredients of perfume kits, hair styling aids and hair sprays, hair deodorants, body creams, foot care products.',1),(5,'5A','Body lotion products applied to the body using the hands (palms), primarily leave-on',1),(6,'5B','Face moisturizer products applied to the face using the hands (palms), primarily leave-on',1),(7,'5C','Hand cream products applied to the hands using the hands (palms), primarily leave-on',1),(8,'5D','Baby Creams, baby Oils and baby talc',1),(9,'6','Products with oral and lip exposure',1),(10,'7A','Rinse-off products applied to the hair with some hand contact',1),(11,'7B','Leave-on products applied to the hair with some hand contact',1),(12,'8','Products with significant anogenital exposure',1),(13,'9','Products with body and hand exposure, primarily rinse off',1),(14,'10A','Household care excluding aerosol products (excluding aerosol/spray products)',1),(15,'10B','Household aerosol/spray products',1),(16,'11A','Products with intended skin contact but minimal transfer of fragrance to skin from inert substrate without UV exposure',1),(17,'11B','Products with intended skin contact but minimal transfer of fragrance to skin from inert substrate with potential UV exposure',1),(18,'12','Products not intended for direct skin contact, minimal or insignificant transfer to skin',1);
/*!40000 ALTER TABLE `IFRACategories` ENABLE KEYS */;
UNLOCK TABLES;

**Comment by xblomx** [comment]
Only way is to make a backup of the db via phpmyadmin or equivalent

**Comment by globaldyne** [comment]
Not a bug - please refer to docker documentation in KB
https://www.jbparfum.com/knowledge-base
